env = Environment()
env.ParseConfig('allegro-config --cflags --libs')
env.Append(CFLAGS=['-std=c99','-fgnu89-inline','-Wall'])
env.Append(CFLAGS=['-g'])
#env.Append(CFLAGS=['-O2'])
env.Program(target = 'fatmage', source = ['main.c','map.c','rules.c','mage.c','game.c'])
env.Program(target = 'mapmaker', source = ['mapedit.c','map.c'])
